### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by marina-cyber** [greraldicus/Time_Series#10]
1. уберите из блокнота любые упоминания о наличии причинно-следственной связи. И вспомните, что такое коинтеграция.
Определение, что вы написали - не соответствует действительности. 

2. Переделайте вывод для VARMA модели. Сказать. что "Как итог - метрики удовлетворительны,..."  нельзя. Они объективно - кошмарные. И графики это подтверждают

Вот это подкорректируйте. И работу зачту.

**Comment by greraldicus** [comment]
Убрал из блокнота любые упоминания конкретно причинно-следственной связи. Поменял определение коинтеграции

Переделал выводы о метриках для VARMA модели

**Comment by marina-cyber** [comment]
проект зачтен
